### ISSUE TITLE
Still checking SVN for update

### ISSUE THREAD

**Issue by syifan** [Multi2Sim/m2s-client-kit#2]
The m2s-client-kit is on github now and the svn repo seems to be removed already. But in the script, it is still using svn info to check if the m2s-client-kit is up-to-date.

Checking for update is questionable anyway. It may prevent user from customizing the client-kit and using it.

**Comment by rafaelubal** [comment]
Yifan,

What script are you referring to? Script 'test-auto.sh' doesn't use SVN anymore. And we recently added option "--offline" and "--local" to avoid this.

**Comment by syifan** [comment]
For example, here
https://github.com/Multi2Sim/m2s-client-kit/blob/master/bin/m2s-cluster.sh#L631
